# frozen_string_literal: true

# fpm-monitor Homebrew formula.
#
# Generated by the release workflow of filoucrackeur/php-fpm-monitor from the
# template Formula/fpm-monitor.rb: version, URL and sha256 are substituted and
# the result is attached to every GitHub release and pushed to the tap
# filoucrackeur/homebrew-fpm-monitor. Install with:
#
#   brew install filoucrackeur/fpm-monitor/fpm-monitor
#   # or directly from a GitHub release:
#   brew install https://github.com/filoucrackeur/php-fpm-monitor/releases/download/v<version>/fpm-monitor.rb

class FpmMonitor < Formula
  desc "PHP-FPM pools monitor (Rust port of fpm-monitor.c)"
  homepage "https://github.com/filoucrackeur/php-fpm-monitor"
  license "MIT"
  version "__VERSION__"

  url "__URL_INTEL__"
  sha256 "__SHA_INTEL__"

  on_arm do
    url "__URL_ARM__"
    sha256 "__SHA_ARM__"
  end

  def install
    if Hardware::CPU.arm?
      bin.install "fpm-monitor-aarch64-apple-darwin" => "fpm-monitor"
    else
      bin.install "fpm-monitor-x86_64-apple-darwin" => "fpm-monitor"
    end
  end

  test do
    assert_match "fpm-monitor", shell_output("#{bin}/fpm-monitor --help")
  end
end
